image: alpine:latest

stages:
  - build

# variables:
#   GIT_SUBMODULE_STRATEGY: normal

before_script:
  - apk update
  - apk add musl-dev meson ninja gcc

debug:
  stage: build
  script:
    - mkdir -p bld/debug
    - cd bld/debug
    - meson --buildtype=debug ../../
    - ninja -v -k0
    - ninja -v test

release:
  stage: build
  script:
    - mkdir -p bld/release
    - cd bld/release
    - meson --buildtype=release ../../
    - ninja -v -k0
    - ninja -v test
